/*
    The sequence of triangle numbers is generated by adding the natural numbers.

    So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
    The first ten terms would be:
    1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

    Let us list the factors of the first seven triangle numbers:
     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

    We can see that 28 is the first triangle number to have over five divisors.
    What is the value of the first triangle number to have over five hundred divisors?

*/

#include <cmath>
#include <iostream>

using namespace std;

int main()
{
    int num, divs, root, i, j;

    num = divs = 0;
    for (i = 1; divs <= 500; ++i)
    {
        divs = 0;
        num += i;

        root = int(sqrt(num));
        for (j = 1; j < root; ++j)
            if (num % j == 0)
                divs += 2;

        if (root*root == num)
            --divs;
    }

    cout << "First triangle number with more than 500 divisors = " << num;

    return 0;
}
